</$objtype/mkfile

CFLAGS=-FTVw

TARG=\
		aecho \
		bcp \
		biocat \
		boom \
		echo \
		env \
		err \
		take \
		runls \
		pnote \
		srvecho \
		srvforkecho

CFILES=\
		aecho.c \
		bcp.c \
		biocat.c \
		boom.c \
		echo.c \
		env.c \
		err.c \
		take.c \
		runls.c \
		pnote.c \
		srvecho.c \
		srvforkecho.c 


</sys/src/cmd/mkmany
